apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "gce"
  name: projectserver-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: projectserver-svc
            port:
              number: 2345
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todos-svc
            port:
              number: 2020
      - path: /todos/done
        pathType: Prefix
        backend:
          service:
            name: todos-svc
            port:
              number: 2020