apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-server-production
  labels:
    environment: production

namespace: production
resources:
- ../../base
- BackupTodoCronJob.yml

patches:
- patch: |-
    - op: replace
      path: /stringData/POSTGRES_HOST
      value: "postgres-svc.production.svc.cluster.local"
  target:
    kind: Secret
    name: postgres-secret